# 全部参数 https://github.com/serverless-components/tencent-website/blob/master/docs/configure.md
component: website
name: myapp
# org: "" # (可选) 用于记录组织信息，默认值为您的腾讯云账户 appid，必须为字符串
app: myapp
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src:
    src: ./src
    dist: ./build
    hook: yarn && yarn build
    index: index.html
    error: index.html
  region: ap-shanghai
  bucketName: myapp-bucket
  protocol: https
  replace: false # 是否覆盖式部署
  cors:
    - allowedOrigins:
        - '*.tencent.com'
        - '*.qcloud.com'
      allowedMethods:
        - PUT
        - POST
        - DELETE
        - HEAD
      allowedHeaders: '*'
      maxAgeSeconds: 0
    - allowedOrigins:
        - '*'
      allowedMethods:
        - GET
      allowedHeaders: '*'
      maxAgeSeconds: 0